version: '3.8'
services:
 front-end:
   build:
     context: ./plms-client/
     dockerfile: Dockerfile
   volumes:
     - ./plms-client:/frontend
   ports:
     - "3000:3000"
   environment:
     - NODE_ENV=${NODE_ENV}
     - API_URL=${API_URL}
     - API_PORT=${API_PORT}
 backend:
    build: plms_server/.
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db_service
 postgres_db_service:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
